# Generated by Django 3.2.16 on 2022-12-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_structure', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='teacher_dt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
