# Generated by Django 3.2.16 on 2022-12-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('type', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor')], default='PROFESSOR', max_length=50, verbose_name='Tipo')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=100, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='Telemóvel')),
                ('address', models.TextField(blank=True, verbose_name='Morada')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
