# Generated by Django 3.2.16 on 2022-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('user',), 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='internal_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Número interno'),
        ),
    ]
