# Generated by Django 3.2.16 on 2023-04-12 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_structure', '0002_schoolclass_teacher_dt'),
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade', models.CharField(choices=[('A', 'Aluno'), ('F', 'Funcionário'), ('P', 'Professor')], default='P', max_length=100, verbose_name='qualidade')),
                ('slug', models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único', unique=True)),
                ('class_number', models.CharField(max_length=200, verbose_name='Número')),
                ('local', models.CharField(max_length=200, verbose_name='Local da ocorrência')),
                ('hora', models.TimeField(verbose_name='Hora da ocorrência')),
                ('dia', models.DateField(verbose_name='Dia da ocorrência')),
                ('comer', models.BooleanField(default=False, verbose_name='Comer na sala de aula.')),
                ('levantar', models.BooleanField(default=False, verbose_name='Levantar-se durante a aula sem autorização.')),
                ('conversar', models.BooleanField(default=False, verbose_name='Perturbar a aula com conversa e brincadeira.')),
                ('entradar_sair_desordeira', models.BooleanField(default=False, verbose_name='Entrar/sair da aula de forma desordeira.')),
                ('patrimonio', models.BooleanField(default=False, verbose_name='Não respeitar o património escolar.')),
                ('recolher_imagens', models.BooleanField(default=False, verbose_name='Recolher/divulgar imagens/sons sem autorização.')),
                ('fumar', models.BooleanField(default=False, verbose_name='Fumar dentro do recinto escolar.')),
                ('regras_espaços', models.BooleanField(default=False, verbose_name='Não cumprir as regras de utilização dos diversos espaços.')),
                ('aparelhos_eletronicos', models.BooleanField(default=False, verbose_name='Utilizar indevidamente o telemóvel ou outro aparelho eletrónico.')),
                ('linguagem', models.BooleanField(default=False, verbose_name='Utilizar linguagem imprópria.')),
                ('ofender_colegas', models.BooleanField(default=False, verbose_name='Ofender verbalmente os colegas.')),
                ('ameacar', models.BooleanField(default=False, verbose_name='Ameaçar/intimidar colegas.')),
                ('recusar_trabalhar', models.BooleanField(default=False, verbose_name='recusar-se a trabalhar.')),
                ('abandonar_aula', models.BooleanField(default=False, verbose_name='abandonar a aula sem autorização do professor.')),
                ('Ofender_prof_fun', models.BooleanField(default=False, verbose_name='Ofender verbalmente professores/funcionários.')),
                ('roubar', models.BooleanField(default=False, verbose_name='Roubar/furtar.')),
                ('nao_obedecer', models.BooleanField(default=False, verbose_name='Não obedecer às indicações do adulto.')),
                ('agredir', models.BooleanField(default=False, verbose_name='Agredir.')),
                ('contextualizacao', models.TextField(blank=True, verbose_name='Breve descrição/contextualização do(s) comportamento(s) incorreto(s):')),
                ('atividade', models.CharField(choices=[('EM', 'em atividade Letiva'), ('FORA', 'fora de atividade letiva')], default='EM', max_length=50, verbose_name='Tipo de atividade')),
                ('ordem_saida', models.BooleanField(default=False, verbose_name='Dada ordem de saída da sala de aula')),
                ('falta', models.BooleanField(default=False, verbose_name='Marcada falta')),
                ('tarefa', models.TextField(blank=True, verbose_name='Encaminhamento com a tarefa:')),
                ('estado', models.CharField(choices=[('ANALISE', 'Em análise'), ('PROCEDIMENTO', 'Procedimento Disciplinar'), ('TERMINADA', 'Terminada')], default='ANALISE', max_length=100, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='accounts.student')),
                ('dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DT', to='accounts.teacher')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma', to='school_structure.schoolclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participação disciplinar',
                'verbose_name_plural': 'Participações disciplinares',
                'ordering': ['user'],
            },
        ),
    ]
