# Generated by Django 3.2.16 on 2023-04-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('game_features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='abandonar_aula',
            field=models.BooleanField(default=False, verbose_name='Abandonar a aula sem autorização do professor.'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='atividade',
            field=models.CharField(choices=[('EM', 'em atividade letiva'), ('FORA', 'fora de atividade letiva')], default='EM', max_length=50, verbose_name='Tipo de atividade'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='estado',
            field=models.CharField(choices=[('ANALISE', 'Em análise'), ('ARQUIVADA', 'Arquivada'), ('CONCLUIDA', 'Participação disciplinar registada'), ('PROCEDIMENTO', 'Procedimento Disciplinar Sumário'), ('EMD', 'Procedimento Disciplinar - EMD')], default='ANALISE', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recusar_trabalhar',
            field=models.BooleanField(default=False, verbose_name='Recusar-se a trabalhar.'),
        ),
        migrations.CreateModel(
            name='ParecerDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único', unique=True)),
                ('parecer', models.CharField(choices=[('1', 'Participação arquivada e sem efeito.'), ('2', 'Ocorrência não frequente e não grave.'), ('3', 'Procedimento disciplinar sumário.'), ('4', 'Procedimento disciplinar sumário - Equipa EMD.')], default='F', max_length=250, verbose_name='Parecer do DT')),
                ('advertencia_verbal_aluno', models.BooleanField(default=False, verbose_name='Advertência verbal ao aluno.')),
                ('comunicacao_EE', models.BooleanField(default=False, verbose_name='Comunicação ao Encarregado de Educação.')),
                ('descricao_acao_dt', models.TextField(blank=True, verbose_name='Breve descrição da(s) ações(s) tomadas(s) pelo DT:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacao', to='game_features.complaint')),
                ('dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiretorTurma', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Parecer do DT',
                'verbose_name_plural': "Pareceres dos DT's",
                'ordering': ['created'],
            },
        ),
    ]
