# Generated by Django 3.2.16 on 2023-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_features', '0002_auto_20230424_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='parecer_dt',
            field=models.BooleanField(default=False, verbose_name='Participação com parecer do DT'),
        ),
    ]
